### PR TITLE
Fix path to configure script

### PR DESCRIPTION
**Pull request by stv0g**
See #341

===

https://github.com/jedisct1/libsodium/issues/848

### CODE REVIEW

**Comment by kpp** [comment]
But can you actually build it on macOS 10.15 Beta (19A471t)?

**Comment by stv0g** [comment]
@kpp The configure error is gone. But now `make check` fails.
See: https://github.com/jedisct1/libsodium/issues/848

**Comment by kpp** [comment]
> But now make check fails.

You mean cargo test --all?

**Comment by stv0g** [comment]
> You mean cargo test --all?

No. `build.rs` calls `make check` by default for all non cross builds.

**Comment by stv0g** [comment]
This might a problem of my compiler though (Xcode GCC). I doubt its related to this issue

**Comment by Dylan-DPC** [comment]
> But now make check fails.

can you paste the error message?

**Comment by kpp** [comment]
I see. Thanks. Let's wait for a new release with this fix from libsodium.

**Comment by stv0g** [comment]
> can you paste the error message?

[compile.log](https://github.com/sodiumoxide/sodiumoxide/files/3422780/compile.log)

**Comment by stv0g** [comment]
@kpp 

> I see. Thanks. Let's wait for a new release with this fix from libsodium.

This PR does not fix the `make check` issue. It is therefore not depending on a libsodium fix.

It is fixing the way `build.rs` is invoking `./configure` which was not done in a portable way.
These are unrelated issues.

**Comment by kpp** [comment]
I agree.

**Comment by kpp** [comment]
bors: r+

**Comment by stv0g** [comment]
Thanks @kpp

**Pull request merged**
