### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by connectkushal**

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by Dylan-DPC** [comment]
bors: try

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by nvesely** [comment]
bors: r+

**Comment by nvesely** [comment]
bors you better listen up, y'hear??!

**Comment by Dylan-DPC** [comment]
bors: ping

**Comment by Dylan-DPC** [comment]
bors: ping

**Comment by Dylan-DPC** [comment]
bors: ping

**Comment by Dylan-DPC** [comment]
Closing and reopening this to see if bors gets a life from it

**Comment by nvesely** [comment]
bors plz be good to us

**Comment by naftulikay** [comment]
lord and savior, bors administrator :pray:

**Pull request closed without merging**
