### PR TITLE
Update libsodium submodule to latest stable branch commit.

### PR DESCRIPTION
**Pull request by adamreichold**

### CODE REVIEW

**Comment by adamreichold** [comment]
Fix for the unrelated Clippy nits in #421

**Comment by kpp** [comment]
We need to update win libs too (https://github.com/sodiumoxide/sodiumoxide/tree/master/libsodium-sys/msvc/Win32/Debug/v140)

**Comment by kpp** [comment]
Thanks! I will compare the hashes of the libs to make sure everything is fine.

**Comment by kpp** [comment]
I can't check binaries because they were republished at 30 June.

**Comment by adamreichold** [comment]
> I can't check binaries because they were republished at 30 June.

Redid the update to the current stable version including the PIC changes.

**Comment by kpp** [comment]
Confirmed.

**Comment by kpp** [comment]
bors: r+

**Pull request merged**
