### PR TITLE
Strip vcpkg support and bump version numbers for release 

### PR DESCRIPTION
**Pull request by dnaq**

### CODE REVIEW

**Comment by kpp** [comment]
Hm. The reason of this CI test was to try to link with vcpkg libsodium

**Comment by kpp** [comment]
I would expect this PR to be clean (only to remove vcpkg support).

**Comment by dnaq** [comment]
This pr won't be merged. I just wanted a branch to push to to run tests.

**Comment by dnaq** [comment]
@tasn pushed the changes.

**Comment by dnaq** [comment]
Closing since #425 is going to get merged.

**Pull request closed without merging**
