### PR TITLE
remove ill-advised gen_nonce functions

### PR DESCRIPTION
**Pull request by GallagherCommaJack**
solves #91 without breaking tests by making functions `pub(crate)` by default, creating `pub` variants where appropriate.

I also changed the default `aead` construction to bring it in line with libsodium's recommendations instead of favoring the less-secure primitive.

### CODE REVIEW

**Comment by kpp** [comment]
Sorry for the delay.

Would you please update your branch to the latest master?

**Comment by kpp** [comment]
bors: r+

**Comment by kpp** [comment]
@GallagherCommaJack would you please create a PR increasing the code coverage?

**Comment by adamreichold** [comment]
> @GallagherCommaJack would you please create a PR increasing the code coverage?

Sorry for the back and forth, but I think the second commit of #395 should actually restore the coverage numbers and avoid the warnings.

**Pull request merged**
