### PR TITLE
Update CHANGELOG 

### PR DESCRIPTION
**Pull request by kpp**

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Since we are doing this : 
1) i'd prefer if we can have separate sections of  the changelog with what changes are added, modified and removed (or deprecated). Maybe a separate section for any dependency change or other version changes. 
2) We don't need to mention all the changes. Some of them are internal and can be omitted from the changelog (such as "happy clippy" and "added CONTRIBUTING.md"

**Comment by kpp** [comment]
1. Maybe
2. I agree, but we'd better track everything to form a nice changelog right before cutting a release.

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by Dylan-DPC** [comment]
bors: r+

**Pull request merged**
