### PR TITLE
Add instructions how to compile for armv7-unknown-linux-musleabihf

### PR DESCRIPTION
**Pull request by kpp**
Thanks to @oherrala 

Closes https://github.com/sodiumoxide/sodiumoxide/issues/238

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Thanks. This is a good start. But we need to add the architecture to the CI process, so we know that the crate works on it and doesn't break in future.

**Comment by kpp** [comment]
> But we need to add the architecture to the CI process, so we know that the crate works on it and doesn't break in future.

@oherrala Can you add it to Travis CI?

**Comment by Dylan-DPC** [comment]
This is trivial so I'm merging it as is. We can add it to the CI in a separate PR.

**Comment by Dylan-DPC** [comment]
bors: r+

**Pull request merged**
