### PR TITLE
Add support for XChaCha20-Poly1305

### PR DESCRIPTION
**Pull request by ccfb3ee765a58cae**
Sodium provides a variant of ChaCha20-Poly1305 with a 192 bit nonce. This exposes these functions in `libsodium-sys` and `sodiumoxide`.

### CODE REVIEW

**Comment by dkulic** [comment]
I wanted to commit this pull request also. Can someone merge this I think this is very useful.

**Comment by dhh1128** [comment]
+1 from me to merge this asap.

**Comment by vimmerru** [comment]
+1 from me too

**Comment by dnaq** [comment]
Please see #203

**Comment by Dylan-DPC** [comment]
@ccfb3ee765a58cae same thing here. Can you resolve the conflicts? Will re-review it after that.

**Comment by Dylan-DPC** [comment]
@ccfb3ee765a58cae any updates? the longer we wait the more conflicts might arise. Will close it in a week if no response.

**Comment by Dylan-DPC** [comment]
Closing this as we never recieved any reply from several months and they would be too many conflicts as we proceed. Will create an issue so that anyone else can pick it up and work from scratch.

**Pull request closed without merging**
