### PR TITLE
Add init support for --target wasm32-wasi

### PR DESCRIPTION
**Pull request by kpp**
Closes: https://github.com/sodiumoxide/sodiumoxide/issues/347

Linked issues: https://github.com/jedisct1/libsodium/issues/872

### CODE REVIEW

**Comment by kpp** [comment]
@sodiumoxide/owners I am confused.

 ```
#[cfg(target_arch = "wasm32")]
fn build_libsodium() {
    std::compile_error!("wasm32")
}

#[cfg(target_arch = "")] // or comment out fn build_libsodium
fn build_libsodium() {
...

```

Then try to compile `cargo build --target wasm32-wasi`:

```
error[E0425]: cannot find function `build_libsodium` in this scope
  --> libsodium-sys/build.rs:64:9
   |
64 |         build_libsodium();
   |         ^^^^^^^^^^^^^^^ not found in this scope
```

Does anybody have an idea why?

**Comment by kpp** [comment]
Alright. Good news. I managed to make all tests pass except for these three:

- https://github.com/sodiumoxide/sodiumoxide/blob/fbfe0392ed569d8da8f17af5bbad2905e2518449/src/utils.rs#L242
- https://github.com/sodiumoxide/sodiumoxide/blob/fbfe0392ed569d8da8f17af5bbad2905e2518449/src/crypto/sign/ed25519.rs#L356
- https://github.com/sodiumoxide/sodiumoxide/blob/fbfe0392ed569d8da8f17af5bbad2905e2518449/src/crypto/sign/ed25519.rs#L387

If someone wants to help me to debug `ed25519::test` tests, here is how you can run them:

```bash
cargo test --target wasm32-wasi -- -- crypto::sign::ed25519::test::test_vectors --nocapture
```

@jedisct1 `mlock` does not work for wasm32. Is it an intended behavior?

**Comment by jedisct1** [comment]
Memory protection doesn't exist in WebAssembly.

It's just one big, linear, MSDOS-like memory region with absolutely zero protection, even against reading/writing to `NULL`.

**Comment by kpp** [comment]
Wontfix

**Pull request closed without merging**
