### PR TITLE
Static bindings [no bindgen]

### PR DESCRIPTION
**Pull request by kpp**
Closes: #280 #232 #267

### CODE REVIEW

**Comment by kpp** [comment]
Waiting for https://github.com/sodiumoxide/sodiumoxide/issues/242 https://github.com/sodiumoxide/sodiumoxide/issues/238 https://github.com/sodiumoxide/sodiumoxide/issues/197 to report whether the fix helped them

**Comment by kpp** [comment]
I don't know how to automate this process. I added libsodium-sys/src/gen.sh but that's all.

**Comment by dnaq** [comment]
I was thinking a manual process, e. g, we get notified (an issue is created
or a post is made to Gitter) whenever a new version of sodium is released.
Someone is responsible for updating the build scripts and regenerating the
bindings.

Would be nice to have everything fully automated and only have to sign off
on a commit, but that seems like future work.

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by DoumanAsh** [comment]
This is really nice, thank you

**Pull request merged**
