### PR TITLE
WIP: Try to build libsodium with cc only

### PR DESCRIPTION
**Pull request by kpp**
unpack libsodium to libsodium-sys/libsodium-1.0.18/ to build it

### CODE REVIEW

**Comment by kpcyrd** [comment]
This would drop support for dynamic linking, right? Can we keep pkg-config to check if libsodium is installed on the system and the version is >= our minimum version, and only fall back to static linking if that isn't the case?

**Comment by kpp** [comment]
It's just a playaround. In https://github.com/sodiumoxide/sodiumoxide/pull/376 I discovered that we compile libsodiumoxide-rs in a wrong way which led to https://github.com/sodiumoxide/sodiumoxide/issues/377. So this example works for my target (linux x86-64) plus --target wasm32-wasi expect for 1 test with mprotect. I want to figure out whether it is possible to build libsodium on our own which can give the user a possibility of xcompilation and we won't need to keep blobs in our code anymore.

**Comment by ryankurte** [comment]
ahh, something like this would be excellent, i had the same issue for the embedded / arm targets so have been patching libsodium-sys with [this](https://github.com/jedisct1/libsodium/compare/master...ryankurte:feature/cargo-compat).

should be easy to add a feature to choose between static or dynamic linking (pkgconfig / lib vs. build from source) if that'd get something like this landed?

**Comment by kpp** [comment]
Seems like this PR won’t get landed

**Comment by kpp** [comment]
Maybe someday in the future I will try it again.

**Pull request closed without merging**
