### PR TITLE
Add github actions

### PR DESCRIPTION
**Pull request by suhr**

### CODE REVIEW

**Comment by kpp** [comment]
@sodiumoxide/owners Hi. Would you please enable Github Actions so we can switch from TravisCI and AppveyorCI to GA? TravisCI is stuck.

**Comment by kpcyrd** [comment]
github actions are already active, they are going to execute after they are merged. I've pushed a branch to trigger an execution and the results can be found here: https://github.com/sodiumoxide/sodiumoxide/actions/runs/325103665

Right now it's failing with:
```
  --- stderr
  thread 'main' panicked at 'Failed to find configure script! Did you clone the submodule at `libsodium-sys/libsodium`?: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libsodium-sys/build.rs:219:89
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by kpcyrd** [comment]
I've resubmitted this PR with some minor fixes in #439 and the actions are running there, but it seems we are unable to merge this until either travis is working again or the "Required" tag is removed.

**Comment by kpp** [comment]
> the "Required" tag is removed

Seems like it's useless in the branch settings because we duplicate them in bors.toml.

**Pull request closed without merging**
