### PR TITLE
Remove useless deprecation annotation

### PR DESCRIPTION
**Pull request by kpcyrd**
This should fix our broken CI.

The change in rustc was caused by https://github.com/rust-lang/rust/pull/78626, further discussion in https://github.com/rust-lang/rust/issues/79304.

### CODE REVIEW

**Review by kpp — APPROVED** [review]

**Comment by kpp** [comment]
> This should fix our broken CI.

Should be merged via github button, right?

**Comment by kpcyrd** [comment]
Bypassing bors shouldn't be neceesary, if this doesn't work I'm going to try reaching out to somebody with more bors experience.

**Comment by kpcyrd** [comment]
I think I figured out the bors issue, bors is pushing to the `staging` branch and waiting for the github actions to complete, but the staging branch wasn't listed in the list of events that trigger the github actions. Lets try this again.

**Comment by kpcyrd** [comment]
bors try

**Comment by Dylan-DPC** [comment]
Generally when we make ci changes it's better to merge it manually via GH because bors uses the old CI configuration to merge it

**Comment by kpcyrd** [comment]
I think this one can be merged with bors because the bors.toml hasn't been modified. Please re-review. :)

**Review by kpp — APPROVED** [review]

**Comment by kpp** [comment]
bors: r+

**Pull request merged**
