### PR TITLE
add bindings for keypair_from_seed for authenticated encryption

### PR DESCRIPTION
**Pull request by agrinman**
This commit adds the bindings for `keypair_from_seed` for libsodium's authenticated encryption (crypto_box_curve25519xsalsa20poly1305).

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
can we get another review on this @sodiumoxide/owners ?

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by jakeschurch** [comment]
Does anyone know when `keypair_from_seed()` is planned to be released? Looking forward to using it.

**Comment by Dylan-DPC** [comment]
@jakeschurch We were waiting for some other PRs to be merged and then issue a release but those seem to be stuck right now. Will wait for a few days and will release a new version next week :+1:

**Pull request merged**
