### PR TITLE
bump versions for release of v0.2.1

### PR DESCRIPTION
**Pull request by SecurityInsanity**
Bumps the versions of libsodium-sys, and sodiumoxide to 0.2.1 to release the fixes for Failing to compile on mac as well as other issues.

I'm not aware of any breaking changes since 0.2.0, so I've marked it as 0.2.1 for now, happy to do anything else required if changes are needed.

### CODE REVIEW

**Comment by kpp** [comment]
How about changelog?

**Comment by SecurityInsanity** [comment]
I don't see any changelong files in the repo? Is there any documentation on where that should go?

**Comment by kpcyrd** [comment]
I'd also like to include #317 in this release if possible.

**Comment by kpp** [comment]
Let me help you with the changelog(from oldest to youngest):
- https://github.com/sodiumoxide/sodiumoxide/pull/296
- https://github.com/sodiumoxide/sodiumoxide/pull/304
- https://github.com/sodiumoxide/sodiumoxide/pull/237
- https://github.com/sodiumoxide/sodiumoxide/pull/306
- https://github.com/sodiumoxide/sodiumoxide/pull/301
- https://github.com/sodiumoxide/sodiumoxide/pull/311
- https://github.com/sodiumoxide/sodiumoxide/pull/314
- https://github.com/sodiumoxide/sodiumoxide/pull/312
- https://github.com/sodiumoxide/sodiumoxide/pull/294
- https://github.com/sodiumoxide/sodiumoxide/pull/315

**Comment by kpp** [comment]
@kpcyrd #315 should be documented in README

**Comment by Dylan-DPC** [comment]
don't worry about the changelog. will add it to the [release notes](https://github.com/sodiumoxide/sodiumoxide/releases) when i create the release.

**Comment by kpp** [comment]
Added changelog: https://github.com/sodiumoxide/sodiumoxide/pull/318

**Comment by kpp** [comment]
@SecurityInsanity please add https://github.com/sodiumoxide/sodiumoxide/pull/317 and https://github.com/sodiumoxide/sodiumoxide/pull/318 to changelog =)

**Comment by Dylan-DPC** [comment]
@kpp that isn't needed. not every change should go into the changelog, just the ones important for the user.

**Comment by Dylan-DPC** [comment]
bors: r+

**Pull request merged**
