### PR TITLE
Fix clippy errors

### PR DESCRIPTION
**Pull request by kpcyrd**
See https://github.com/sodiumoxide/sodiumoxide/pull/450

### CODE REVIEW

**Comment by kpp** [comment]
Would you please fix all clippy errors?

**Comment by kpcyrd** [comment]
@kpp done! missed the warning in the tests because I only checked `cargo clippy` :)

**Review by kpp — APPROVED** [review]

**Comment by kpp** [comment]
bors: r+

**Comment by kpp** [comment]
> @kpp done! missed the warning in the tests because I only checked `cargo clippy` :)

Good to know our CI does its job:)

**Comment by kpp** [comment]
bors: retry

**Comment by kpcyrd** [comment]
I'm wondering if something changed in github actions and cherry-picked the commit from #452, let's see if that fixes the issue.

**Comment by kpcyrd** [comment]
bors try

**Review by kpp — APPROVED** [review]

**Comment by kpp** [comment]
bors: r+

**Pull request merged**
