### PR TITLE
Remove gh-pages support

### PR DESCRIPTION
**Pull request by kpp**
Use docs.rs instead

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
We already have a docs.rs, but it is broken due to a [build failure](https://docs.rs/crate/sodiumoxide/0.1.0)

**Comment by kpp** [comment]
Woah. Why did it break?

**Comment by Dylan-DPC** [comment]
https://docs.rs/crate/sodiumoxide/0.1.0/builds/122853

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by Dylan-DPC** [comment]
Damn. So AppVeyor has a build limit of 60 mins for free plan and we are exceeding that. We need to find a way to trim the build time or move to travis for windows builds (or there is something wrong with our config which I doubt)

**Comment by kpp** [comment]
bors: r+

**Comment by kpcyrd** [comment]
@dnaq please make sure you revoke the token that was used for this :)

**Comment by dnaq** [comment]
The token is revoked now

**Pull request merged**
