### PR TITLE
Fix unused warnings as  is always defined but not always exported

### PR DESCRIPTION
**Pull request by adamreichold**
Warnings like https://travis-ci.org/sodiumoxide/sodiumoxide/jobs/615562099#L255

### CODE REVIEW

**Comment by kpp** [comment]
How about unit tests? The report showed 0.3% coverage decreasing https://github.com/sodiumoxide/sodiumoxide/pull/373#issuecomment-529317478

**Comment by adamreichold** [comment]
> Maybe it would be better than hiding warnings?

Unit tests won't make these errors go away: Tests are compiled using `#[cfg(test)]` and hence a normal build of this library, e.g. as a dependency for just via `cargo clippy`, will still produce them.

This is dead code after all as non-public functions can't be used by anything outside the crate itself and adding tests does not change that. Or put differently, why test something that nobody using this library can actually use.

I think the cleaner way would be to not define the the internal functions at all. Maybe actually provide a generic method like
```
fn gen_random_nonce<N: Default + AsMut<[u8]>>() -> N {
  let mut n = N::default();
  randombytes_into(n.as_mut());
  n
}
```
instead of generating via a macro? But this would imply implementing `AsMut<[u8]>` for `new_type!{nonce ..}`...

> How about unit tests? The report showed 0.3% coverage decreasing [#373 (comment)](https://github.com/sodiumoxide/sodiumoxide/pull/373#issuecomment-529317478)

I can add more unit tests if you like but I have to admit I feel that they should have part of the original MR. Can you be specific which unit tests you'd like to see?

**Comment by kpp** [comment]
> I feel that they should have part of the original MR

Good idea

**Comment by adamreichold** [comment]
> Maybe actually provide a generic method like

I added another commit here that implements the generic method (c.f. the commit message for the details) and avoid defining any unused functions or extending the public interface of the nonce types. I feel like this is a nicer solution overall, but it admittedly is also more involved than the status quo.

**Comment by kpp** [comment]
Looks like the PR did not affect coverage

**Comment by adamreichold** [comment]
> Looks like the PR did not affect coverage

Different from what I implied earlier, the loss of coverage in #373 was not because of the unused functions but due to the forwarding functions `gen_nonce` which still seem to be in need of additional unit tests as the unit tests generated by the macros do not cover them anymore. But then these unit tests would be copies of the ones created by the macros...

**Comment by adamreichold** [comment]
> But then these unit tests would be copies of the ones created by the macros...

Actually, I'll try to add something that asserts on the nonce length which should actually be somewhat sensible and should fix the coverage.

**Comment by adamreichold** [comment]
> > But then these unit tests would be copies of the ones created by the macros...
> 
> Actually, I'll try to add something that asserts on the nonce length which should actually be somewhat sensible and should fix the coverage.

Did that. Also factored out the random nonce generation from the `box_` and `secretbox` modules.

**Comment by kpp** [comment]
Ready to merge?

**Comment by adamreichold** [comment]
> Ready to merge?

Yes, definitely. I was just adding more cosmetics. Sorry for the large number of force-pushes. I just try to get review as early as possible and then always find more nits to fix.

**Comment by kpp** [comment]
bors: r+

**Pull request merged**
