### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by connectkushal**

### CODE REVIEW

**Comment by samscott89** [comment]
Thank you for adding this.
We will also need to add a CoC, and link these both to the README. Perhaps you could do the latter for this doc, but we can add the code of conduct as a fresh issues.

**Comment by connectkushal** [comment]
ok. I will add a link to readme after this this file is completed and merged.

**Comment by Dylan-DPC** [comment]
The link is added in #262

**Comment by Dylan-DPC** [comment]
bors: r+

**Pull request merged**
