### PR TITLE
Added ed25519 to x25519 conversion methods

### PR DESCRIPTION
**Pull request by sekhat**
To address the change requests for PR #362

Since the original author of the pull request hadn't responded. I've made the changes here.

### CODE REVIEW

**Comment by sekhat** [comment]
Checks seem to have failed due to network errors when cargo was fetching stuff. Not sure if I'm able to rerun them.

**Comment by adamreichold** [comment]
> Not sure if I'm able to rerun them.

You could amend your last commit (without any changes) and force-push the result to trigger the CI again.

**Comment by sekhat** [comment]
Checks seem fine now :)

**Review by kpp — APPROVED** [review]

**Comment by kpp** [comment]
bors: r+

**Comment by kpp** [comment]
@sekhat btw, did you see https://github.com/sodiumoxide/sodiumoxide/pull/456 ?

**Pull request merged**
