### PR TITLE
update gitignore file

### PR DESCRIPTION
**Pull request by kinggoesgaming**

### CODE REVIEW

**Comment by kinggoesgaming** [comment]
Yea you are right I will add them back (probably with a little structure to them)

**Comment by kinggoesgaming** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
er.....

bors: try

**Comment by kinggoesgaming** [comment]
Did I break bors?

bors: ping

**Comment by kinggoesgaming** [comment]
bors: r+

**Comment by Dylan-DPC** [comment]
bors: r+

**Comment by kinggoesgaming** [comment]
bors is apparently crashing...

image

This needs to be reported to bors team

**Comment by Dylan-DPC** [comment]
There is some issue with bors, so merging this without it.

**Pull request merged**
